/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ../../Downloads/old_vintage_microphon_0118195442_texture.glb --types model.tsx 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh;
  };
  materials: {
    mesh_0: THREE.Material;
  };
};

export default function Mic(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/mic.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  );
}

useGLTF.preload("/old_vintage_microphon_0118195442_texture.glb");
